FRONTENDBOOTCAMP-13th/JS-08-bibim

README.md

📝 docs: modify docs

---

README.md

- 수업 중 진행한 테스트 진행으로 README.md 파일 발자취 기록

📝 docs: Leave a footprint in the README file

---

README.md

📝 docs: modify docs - kyungmin

---

.github/ISSUE_TEMPLATE/commit-rule.md
src/news-page.html

- [[commit-rule.md](http://commit-rule.md/)](http://commit-rule.md/) 마크다운 커밋 내용 추가
- 뉴스 기사 상세 페이지 레이아웃과 콘텐츠 구현
- 뉴스 기사 상세 페이지 레이아웃 여백 추가 및 구분선 추가
- 뉴스 퀴즈 레이아웃 추가 및 해더 HTML 추가

Feature/11-news-page Added commit guideline documentation and implemented & refined the layout and content for the news article and quiz pages.

---

package-lock.json
package.json
src/components/quiz.html
src/typescript/deepseekQuiz.js

🎨 feat: Implementing Quiz

---

prettier.config.js
src/components/footer.html

- footer conponent 제작
resolves #33

💄 style: Modifying Minimum Width

---

prettier.config.js
src/components/category.html
src/components/header.html
src/pages/main-page.html
src/pages/news-page.html

- Applied Tailwind CSS to the header navigation component
- Updated prettier.cjs printWidth setting to 500
- Applied Tailwind CSS to the category tab component
- Added a header to news-page.html
- Added main-page.html
- 헤더 네비게이션 컴포넌트 tailwind css 적용
- prettier.cjs printWidth: 500으로 수정
- 카테고리 탭 컴포넌트 tailwind css 적용
- news-page.html header 추가
- main-page.html 추가

🎨 feat: Add Tailwind, update Prettier, add pages

---

prettier.config.js
src/pages/my-page.html
src/typescript/deepseekQuiz.js
src/typescript/my-page.ts

🎨 feat: Implementing Calendar and Points on My Page

---

src/pages/toggle-menu.html
src/typescript/toggle-menu.ts

- Added hamburger menu
- Implemented "View My Points" section
- Added "My Attendance Calendar"
- Added "Favorite Articles" feature
헤더에 마이페이지 → 사이드 메뉴 변경
1) 햄버거 바 추가
2) 내 포인트 모아 보기 구현
3) 내 출석 달력 추가
4) 즐겨찾는 기사 추가 (열어본 기사로 추후 변경 가능)

🎨 feat: Converted the My Page section into a side menu with features like points, attendance calendar, and favorites.

---

src/components/quiz.html
src/typescript/quiz.ts

- 퀴즈 기능 완성
- 딥시크 API를 이용해서 3개의 문제를 내도록 설정
- 문제를 맞히면 점수를 얻게 설정
resolves #46

🎨 feat: Implementing Quiz feature

---

src/components/history.html
src/typescript/history.ts
src/typescript/main-page.ts

- 메인 페이지에서 기사를 읽으면 해당 내용이 히스토리 ldb에 저장되도록 구현
resolves #47

🎨 feat: Implementing History Feature and Component

---

src/pages/main-page.html
src/typescript/main-page-test.ts
src/typescript/search-page.ts

- 현재시간부터 경과된 시간에따라 다른색으로 나타내기, 퀴즈랑 즐겨찾기 버튼생성, 메인페이지 접근성 리팩도링
resolves #47

🎨 feat: Time-specific colors on news cards, quiz buttons and favorite buttons, and category toggle function

---

src/pages/main-page.html
src/pages/search-page.html

💄 style:  main-page style update

---

src/components/quiz.html
src/pages/quiz.html
src/typescript/quiz.ts

🎨 feat: Complementing Quiz Features

---

src/typescript/main-page.ts
src/typescript/quiz.ts

🎨 feat: Connect main and quiz pages

---

src/pages/main-page.html
src/pages/quiz.html
src/pages/toggle-menu.html
src/typescript/main-page.ts
src/typescript/quiz.ts
src/typescript/toggle-menu.ts
src/typescript/updatePoint.ts

🎨 feat: Implementing Point feature 

---

src/pages/question-game.html
src/typescript/question-game.ts

🎨 feat: Category game development

---

src/typescript/main-page.ts

- 메인 페이지의 이미 본 기사 gray-300 배경처리
resolves #71

🎨 feat: main-page local storage handling

---

src/pages/main-page.html
src/pages/quiz.html
src/typescript/main-page.ts
src/typescript/quiz.ts

🎨 feat: Implementing Recommanded news Feature

---

src/pages/main-page.html

- main page header UI 최종 수정 완료

🩹 modify: Final update to main page header

---

src/pages/quiz.html
src/typescript/main-page.ts
src/typescript/quiz.ts

- Fix a bug that blackens out the screen when you press My Page
- Correct error messages intuitively
- Reduce the number of recommended articles
resolves #78

🐛 bugfix: Fix Quiz Page Bug

---

src/pages/main-page.html
src/typescript/main-page.ts

♻️ refactor: refeactoring main-page

---

index.html
vite.config.js

🚀 deploy: Deploy stuff

---

index.html
src/pages/main-page.html
src/pages/quiz.html
src/typescript/toggle-menu.ts

🎨 feat: Implementing Trophy Feature

---

src/pages/game/baseball-game.html
src/pages/game/game-page.html
src/pages/game/question-game.html
src/pages/game/soccer-game.html
src/pages/main-page.html
src/typescript/baseball-game.ts
src/typescript/soccer-game.ts

🎨 feat: create game page

---

index.html
src/pages/game/baseball-game.html
src/pages/game/game-page.html
src/pages/game/question-game.html
src/pages/game/soccer-game.html
src/pages/main-page.html
src/pages/quiz.html
src/typescript/toggle-menu.ts

🐛 bugfix: Trophy bug, Footer bug

---

src/pages/main-page.html
src/typescript/toggle-menu.ts

🎨 feat: Add toggle menu tab functionality

---

src/pages/main-page.html
src/typescript/toggle-menu.ts

♻️ refactor: separate toggle menu logic

---

src/pages/main-page.html

🩹 modify: Modify main page color

---

src/pages/main-page.html
src/typescript/toggle-menu.ts

- 히스토리 기능을 추가하였습니다.
resolves #99

🎨 feat: history function

---

src/pages/main-page.html
src/pages/quiz.html
src/typescript/quiz.ts

- 메인페이지랑 퀴즈페이지 검색창 ui 변경 및 통일
- 퀴즈창 색상이랑 스타일 변경(미완) 
resolves #107

💄 style: main-page and quiz-page search style change

---

index.html
src/pages/main-page.html
src/pages/quiz.html

index페이지, quiz페이지, main페이지 검색바 리뉴얼
resolves #116

💄 style: search UI renewal

---

src/typescript/quiz.ts

- quiz.ts에서 퀴즈 정답과 오답시의 border 색상 변화
- 퀴즈리스트 hover시에 색상과 border 색상 gamePage랑 동일하게 수정
resolves #119

💄 style: quiz.ts UI modify

---

src/typescript/main-page.ts
src/typescript/toggle-menu.ts

🐛 bugfix: Fixing bugs where points are not updated immediately

---

src/pages/game/baseball-game.html
src/pages/game/game-page.html
src/pages/game/question-game.html
src/pages/game/soccer-game.html

- game page ui변경
resolves #127

💄 style: game style development

---

src/typescript/main-page.ts
src/typescript/quiz.ts
src/typescript/updatePoint.ts

🐛 bugfix: Fix model usage bugs

---

src/typescript/toggle-menu.ts

🐛 bugfix: Fix Bubbling Bugs

---

src/typescript/main-page.ts

🎨 feat: Remove card area click function

---

README.md

📝 docs: update README file
